language: c

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: gcc-4.8
  - os: linux
    compiler: gcc-5
  - os: linux
    compiler: gcc-6
  - os: osx
    env: INSTALL=gcc48
    compiler: gcc-4.8
  - os: osx
    env: INSTALL=gcc
    compiler: gcc-6
    osx_image: xcode8

script: 
- make
- ./hello